CRITICAL - 2024-04-12 00:33:33 --> ArgumentCountError: Too few arguments to function App\Controllers\Prueba::holaTodos(), 0 passed in C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php on line 943 and exactly 2 expected
in APPPATH\Controllers\Prueba.php on line 12.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Prueba->holaTodos()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prueba))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-12 01:12:04 --> DivisionByZeroError: Division by zero
in APPPATH\Controllers\Prueba.php on line 14.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Prueba->holaTodos()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prueba))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-12 01:45:57 --> ErrorException: Undefined variable $ky
in APPPATH\Views\vista.php on line 6.
 1 APPPATH\Views\vista.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $ky', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\vista.php', 6)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\vista.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('vista', [], true)
 5 APPPATH\Controllers\Prueba.php(16): view('vista')
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Prueba->holaTodos()
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prueba))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-12 01:46:43 --> ErrorException: Undefined variable $ky
in APPPATH\Views\vista.php on line 6.
 1 APPPATH\Views\vista.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $ky', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\vista.php', 6)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\vista.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('vista', [], true)
 5 APPPATH\Controllers\Prueba.php(16): view('vista')
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Prueba->holaTodos()
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prueba))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-12 02:11:05 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'noticias', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter4\system\Model.php(243): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter4\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\codeigniter4\app\Models\Nuevomodelo.php(11): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\codeigniter4\app\Controllers\Prueba.php(18): App\Models\Nuevomodelo->obtenerNoticia()
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(943): App\Controllers\Prueba->holaTodos()
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prueba))
#10 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codeigniter4\system\Model.php(243): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codeigniter4\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\codeigniter4\app\Models\Nuevomodelo.php(11): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\codeigniter4\app\Controllers\Prueba.php(18): App\Models\Nuevomodelo->obtenerNoticia()
#7 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(943): App\Controllers\Prueba->holaTodos()
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prueba))
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-12 02:11:05 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `noticia`', [], false)
 3 SYSTEMPATH\Model.php(243): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\Nuevomodelo.php(11): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Prueba.php(18): App\Models\Nuevomodelo->obtenerNoticia()
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Prueba->holaTodos()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prueba))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-12 02:11:28 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'noticias', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter4\system\Model.php(243): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter4\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\codeigniter4\app\Models\Nuevomodelo.php(11): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\codeigniter4\app\Controllers\Prueba.php(18): App\Models\Nuevomodelo->obtenerNoticia()
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(943): App\Controllers\Prueba->holaTodos()
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prueba))
#10 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codeigniter4\system\Model.php(243): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codeigniter4\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\codeigniter4\app\Models\Nuevomodelo.php(11): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\codeigniter4\app\Controllers\Prueba.php(18): App\Models\Nuevomodelo->obtenerNoticia()
#7 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(943): App\Controllers\Prueba->holaTodos()
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prueba))
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-12 02:11:28 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `noticia`', [], false)
 3 SYSTEMPATH\Model.php(243): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\Nuevomodelo.php(11): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Prueba.php(18): App\Models\Nuevomodelo->obtenerNoticia()
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Prueba->holaTodos()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prueba))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
